### ISSUE TITLE
ValueError: keyType 24 doesn't handled

### ISSUE THREAD

**Issue by TaihouKai** [titov-vv/tdecypt#1]
Hi, I tried so hard to find some tool to decrypt Telegram data, and I ended up here.
Is this repo still working? I got the following error while running:

```
$ python main.py -p [profile]
Traceback (most recent call last):
  File "/Users/[username]/Desktop/Workspace/im-forensics/tdecrypt/main.py", line 35, in <module>
    main()
  File "/Users/[username]/Desktop/Workspace/im-forensics/tdecrypt/main.py", line 28, in main
    profile.load()
  File "/Users/[username]/Desktop/Workspace/im-forensics/tdecrypt/tprofile.py", line 209, in load
    map_elements = self.__ReadMap(decrypted_map)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[username]/Desktop/Workspace/im-forensics/tdecrypt/tprofile.py", line 154, in __ReadMap
    raise ValueError(f"keyType {keyType} doesn't handled")
ValueError: keyType 24 doesn't handled
```
----
PS: I did the following changes to make the repo at least runnable:
* Line 5 of `tprofile.py`: `from Cryptodome.Cipher import AES`
* Line 2 & 3 of `main.py`: ...`/Users/[username]/Library/Application Support/Telegram Desktop/tdata`...

**Comment by titov-vv** [comment]
I haven't touched it for about a year... Most probably telegram added some new type of message in recent releases. 
It is better to check in Telegram source code, but I don't have enough time for it now.
